### ISSUE TITLE
ReportUserAssignedLicenses-MgGraph.PS1 - Fixed a bug which the column "Direct assigned licenses" is empty.

### ISSUE THREAD

**Issue by aigolang** [12Knocksinna/Office365itpros#104]
`# ReportUserAssignedLicenses-MgGraph.PS1
# V1.8 11-Mar-2024 Fixed a bug which the column "Direct assigned licenses" is empty.

## >>> Define Custom path at the begining >>>
$skuDataPath = "C:\temp\SkuDataComplete.csv"
$servicePlanPath = "C:\temp\ServicePlanDataComplete.csv"

$CSVOutputFile = "C:\temp\Microsoft365LicensesReport.CSV"
$ReportFile = "C:\temp\Microsoft365LicensesReport.html"
## <<< Define Custom path at the begining <<<

# Connect to the Graph, specifing the tenant and profile to use - Add your tenant identifier here
Connect-MgGraph -Scope "Directory.AccessAsUser.All, Directory.Read.All, AuditLog.Read.All"

[Array]$Skus = Get-MgSubscribedSku
### $Skus | Select SkuId, SkuPartNumber  | Export-Csv -NoTypeInformation $skuDataPath
$SPData = [System.Collections.Generic.List[Object]]::new()
ForEach ($S in $Skus) {
   ForEach ($SP in $S.ServicePlans) {
     $SPLine = [PSCustomObject][Ordered]@{  
         ServicePlanId = $SP.ServicePlanId
         ServicePlanName = $SP.ServicePlanName
         ServicePlanDisplayName = $SP.ServicePlanName }
     $SPData.Add($SPLine)
 }
}
$SPData | Sort ServicePlanId -Unique | Export-csv $servicePlanPath -NoTypeInformation

**Comment by aigolang** [comment]
1. Move all file path object defination to the beginning.
2. Update line as: $Skus | Select SkuId, SkuPartNumber  | Export-Csv -NoTypeInformation $skuDataPath

Just like this:
# V1.8 11-Mar-2024 Fixed a bug which the column "Direct assigned licenses" is empty.

## >>> Customize >>>
$skuDataPath = "C:\temp\SkuDataComplete.csv"
$servicePlanPath = "C:\temp\ServicePlanDataComplete.csv"

$CSVOutputFile = "C:\temp\Microsoft365LicensesReport.CSV"
$ReportFile = "C:\temp\Microsoft365LicensesReport.html"
## <<< Customize <<<

# Connect to the Graph, specifing the tenant and profile to use - Add your tenant identifier here
Connect-MgGraph -Scope "Directory.AccessAsUser.All, Directory.Read.All, AuditLog.Read.All"

[Array]$Skus = Get-MgSubscribedSku
# Generate CSV of all product SKUs used in tenant
$Skus | Select SkuId, SkuPartNumber  | Export-Csv -NoTypeInformation $skuDataPath
# Generate list of all service plans used in SKUs in tenant
$SPData = [System.Collections.Generic.List[Object]]::new()
ForEach ($S in $Skus) {
   ForEach ($SP in $S.ServicePlans) {
     $SPLine = [PSCustomObject][Ordered]@{  
         ServicePlanId = $SP.ServicePlanId
         ServicePlanName = $SP.ServicePlanName
         ServicePlanDisplayName = $SP.ServicePlanName }
     $SPData.Add($SPLine)
 }
}
$SPData | Sort ServicePlanId -Unique | Export-csv $servicePlanPath -NoTypeInformation


Function Get-LicenseCosts {...

**Comment by aigolang** [comment]
Just like this:
![image](https://github.com/12Knocksinna/Office365itpros/assets/32412778/ae36a21b-3cde-46ea-87b3-f69b64f63ede)

**Comment by 12Knocksinna** [comment]
Direct assigned licenses seem to be working OK in my version. What  exact changes did you want to make?
