### ISSUE TITLE
SharePointUsage does not give Site URLs  - TeamsGroupsActivityReportV5.PS1

### ISSUE THREAD

**Issue by vishwasdm** [12Knocksinna/Office365itpros#105]
Hi,

I really loved this script which pulls out all teams activity. However, since last few months, the script does not return the site URLs because of the issue [SP676147 -Admins may see incomplete usage reports for SharePoint Online and OneDrive for Business] and Microsoft came up with a workaround to get the site URLs again with another PS script - (https://learn.microsoft.com/en-US/microsoft-365/admin/activity-reports/resolve-site-urls?view=o365-worldwide#update-report-powershell-script). You may have to include the script to fetch the site URLs.

Thank you
Vishwa

**Comment by 12Knocksinna** [comment]
Caused by Microsoft. See https://office365itpros.com/2024/02/19/sharepoint-usage-data-issue/. We have to wait for them to fix the issue.

**Comment by vishwasdm** [comment]
They have suspended the investigation by providing an alternative solution(once usage reports are pulled in then there is a script to run the pull the Site URLs ) but not a permanent fix.

Admins may see incomplete usage reports for SharePoint Online and OneDrive for Business
ID: SP676147
Issue type: Advisory 	

Status
Investigation Suspended	

Impacted services
SharePoint Online	

Details
Title: Admins may see incomplete usage reports for SharePoint Online and OneDrive for Business

User impact: Admins may see incomplete usage reports for SharePoint Online and OneDrive for Business.

More info: SharePoint and OneDrive URLs may not be displayed in some usage reports. The following report types may be impacted:

- SharePoint site usage reports

- OneDrive for Business site usage reports

- Data Access Governance (DAG) impact was remediated on Saturday, October 21, 2023, reports created during the impact timeframe can be re-generated to include URLs.

As a workaround, admins with appropriate access can use the SharePoint REST API or Microsoft Graph API to retrieve information about site IDs referenced in the affected reports.

Here is an example SharePoint REST API request that retrieves information about the Contoso site with site ID 15d43f38-ce4e-4f6b-bac6-766ece1fbcb4: https://contoso.sharepoint.com/_api/v2.1/sites/contoso.sharepoint.com,15d43f38-ce4e-4f6b-bac6-766ece1fbcb4

The Microsoft Graph API can be used to list SharePoint sites or retrieve information about a specific site ID: https://learn.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0

Examples:

- https://graph.microsoft.com/v1.0/sites?search=*&$select=sharepointIds

- https://graph.microsoft.com/v1.0/sites/{siteId}

The Microsoft Graph API can be used to retrieve information about a given user’s OneDrive for Business site: https://learn.microsoft.com/en-us/graph/api/resources/drive?view=graph-rest-1.0

Example:

- https://graph.microsoft.com/v1.0/users/{userId}/drives?$select=sharepointIds

Final status: Additional resources and guidance are being provided for admins to perform a robust set of optional workaround actions here: https://learn.microsoft.com/en-US/microsoft-365/admin/activity-reports/resolve-site-urls?view=o365-worldwide. 

We’re continuing an investigation focused on the restoration of the URLs into the affected Site Usage reports. We expect that this process will continue for an extended period of time. We’ll provide additional notifications through standard update channels as our work on the necessary changes progresses.

More general information about site usage reports is provided here: https://learn.microsoft.com/en-US/microsoft-365/admin/activity-reports/sharepoint-site-usage-ww?view=o365-worldwide and here https://learn.microsoft.com/en-us/microsoft-365/admin/activity-reports/onedrive-for-business-usage-ww?view=o365-worldwide.

Scope of impact: Your organization is affected by this event, and admins attempting to access affected usage reports may be unable to view URLs within the reports.

Start time: Thursday, September 21, 2023, at 4:15 AM UTC.

End time: Friday, March 8, 2024, at 11:30 PM UTC.

Root cause: A previous change made to mitigate an unrelated service side issue removed the flow of URLs for the affected usage reports, resulting in impact.

Next steps:

- We're continuing to work on the necessary changes required to restore this aspect of the service, and we’ll provide additional notifications through standard update channels as they become available.

This is the final update for this event.	

Is this message helpful?
