### ISSUE TITLE
Report-UserPasswordChanges.PS1

### ISSUE THREAD

**Issue by KaveSys** [12Knocksinna/Office365itpros#114]
Hello,
Using the script in subject, after some users doesn't show the state of MFA for the users, see screenshot:
![EmptyMFA](https://github.com/12Knocksinna/Office365itpros/assets/152485719/664a4dce-83b3-4119-a4e6-d303f07bf037)

**Comment by 12Knocksinna** [comment]
You'll have to do some debugging because I can't see the details of those users. Check an account that works and then check one that doesn't and maybe you'll see something that could be causing the problem.

**Comment by KaveSys** [comment]
I obviously remove the informations about the users that weren't populated. I mean that after about 500 people, the remaining were not populated. Seems that there are some issues regarding the paging.

**Comment by KaveSys** [comment]
I

**Comment by 12Knocksinna** [comment]
I just updated the script to change the call to fetch authentication method data for users to get everything that the Graph can send. Try the change.

[array]$MFAData = Get-MgBetaReportAuthenticationMethodUserRegistrationDetail -All -PageSize 999
