### ISSUE TITLE
Get-GraphData error - The specified value is not valid in the 'SslPro tocolType' enumeration

### ISSUE THREAD

**Issue by joostvdlinden** [12Knocksinna/Office365itpros#117]
First of all, thanks for all the efforts put into creating this script. It is very useful.

When I try to run the script I get the following error upon quite a lot of goups:

> Get-GraphData : System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.ArgumentException: The specified value is not valid in the 'SslPro
> tocolType' enumeration.
> Parameter name: sslProtocolType
>    at System.Net.Security.SslState.ValidateCreateContext(Boolean isServer, String targetHost, SslProtocols enabledSslProtocols, X509Certificate serverCertificate, X509CertificateCollection clientCerti
> ficates, Boolean remoteCertRequired, Boolean checkCertRevocationStatus, Boolean checkCertName)
>    at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
>    at System.Net.TlsStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback asyncCallback, Object asyncState)
>    at System.Net.ConnectStream.WriteHeaders(Boolean async)
>    --- End of inner exception stack trace ---
>    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
>    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
> At line:570 char:28
> + ...            $TeamDetails = Get-GraphData -AccessToken $Token -Uri $Uri
> +                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-GraphData

The issue does not persist for all groups.

Would this be a local issue on my machine? If so, what could I do to resolve this issue?

**Comment by 12Knocksinna** [comment]
How many groups are we dealing with here? It could be a matter that the Graph API call is failing because of a network issue.

**Comment by joostvdlinden** [comment]
> How many groups are we dealing with here? It could be a matter that the Graph API call is failing because of a network issue.

The tenant has around 282 Microsoft 365 groups.

**Comment by 12Knocksinna** [comment]
Has the error reappeared? The script is being used by tenants with > 20,000 groups, so the code is capable of handling that number of groups. What version of the script are you using?

**Comment by 12Knocksinna** [comment]
Closed. I assume the fault did not reappear.
