### ISSUE TITLE
$counter never updated

### ISSUE THREAD

**Issue by dyuburg** [12Knocksinna/Office365itpros#119]
Hello, your $counter value never updates. You may want to change this two lines
https://github.com/12Knocksinna/Office365itpros/blob/087f6919a0374089df99b9c298bbd824bf589dc6/CleanUpMailbox-Graph.PS1#L222 $counter =1
https://github.com/12Knocksinna/Office365itpros/blob/087f6919a0374089df99b9c298bbd824bf589dc6/CleanUpMailbox-Graph.PS1#L341 } $counter++

**Comment by 12Knocksinna** [comment]
I don't think that counter variable is ever used, so I simply removed it.
