### ISSUE TITLE
GetGraphUserStatisticsReport

### ISSUE THREAD

**Issue by itpro-tips** [12Knocksinna/Office365itpros#12]
Hello Tony,
Careful with the usertype -eq "member" because it can be  [null in old tenants](https://itpro-tips.com/2019/usertype-empty-usertype-vide/)

**Comment by 12Knocksinna** [comment]
That's true. However, this is an example of the kind of bulletproofing that people should consider when they download from this repository. I write code to illustrate principles instead of creating complete solutions... but I will fix this in due course.

**Comment by 12Knocksinna** [comment]
Closed because I consider that this is an issue that will be addressed in the tenants affected.
