### ISSUE TITLE
TeamsGroupsActivityReport.ps1 -> Date format to 's'

### ISSUE THREAD

**Issue by PorreKaj** [12Knocksinna/Office365itpros#14]
Hi,

Please consider using "-format s" in all date outputs.
Doing so will make the relevant columns instantly sortable even if some rows contain No items found/No Chats

**Comment by 12Knocksinna** [comment]
I think that's a choice that a tenant can make. If you want to use format s, go ahead and create your own version of the script.

**Comment by PorreKaj** [comment]
With some fields populated bu text, the column will never be sortable as dates.
With format s the column can be sorted alphabetically and still be in chronological order.

But ok :-)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by 12Knocksinna** [comment]
There's nothing to stop you sorting the dates as dates. For example:

$Report | Sort {$_.LastConversation -as [DateTime]} -Descending |ft Groupname, lastconversation
