### ISSUE TITLE
Get-graphdata

### ISSUE THREAD

**Issue by kendalf1** [12Knocksinna/Office365itpros#17]
@12Knocksinna  - Sorry if this isn't where I should be asking a question.... but

In your Teamsgroupactivityreport - the one that uses Graph, where do I get the function that you use
Get-graphdata

I can't find that function anywhere.

**Comment by 12Knocksinna** [comment]
It's at the bottom of the script.

[cid:image001.png@01D6D7DC.6EF0F370]

**Comment by 12Knocksinna** [comment]
And you need the TeamsGroupsActivityReportV5-Graph script, not the other version.

**Comment by kendalf1** [comment]
Thanks @12Knocksinna , sorry for you having to point out the obvious to me....

Thanks for this! It's running right now, I managed to give it the right permissions in graph to get it to work.... sweet!

I'm sure you realize this but those creds are in the script.  I assume they are for a test environment....  Have you ever stored credentials in key vault for a Powershell script?

**Comment by 12Knocksinna** [comment]
Yes. The intention was to build a script that could be run in any tenant because the Graph permissions were not particularly heavy. But in any case, the credentials have been changed from the real values. They're only there to allow people to see what they should be adding.
