### ISSUE TITLE
Error while running the script TeamsGroupsActivityReportV5.PS1

### ISSUE THREAD

**Issue by altonbrinja** [12Knocksinna/Office365itpros#24]
![image](https://user-images.githubusercontent.com/81647910/113041839-6f029a80-9168-11eb-904c-ba3411c8988d.png)

**Comment by themarkdiesel** [comment]
Yep, getting the same.

**Comment by JH050** [comment]
You probably get this error because you did not change the values at lines 133, 134 and 135 in the code. You need to change them to the id's of your App that you registered in Azure Active Directory.

**Comment by 12Knocksinna** [comment]
Yep. You've got to have the right tenant id, app id, and app secret to run any Graph-based script. And you've got to make sure that the app you use has the right permissions.
