### ISSUE TITLE
Issue with the script ReportManagersAndDirectReports

### ISSUE THREAD

**Issue by altonbrinja** [12Knocksinna/Office365itpros#25]
![image](https://user-images.githubusercontent.com/81647910/113043501-880c4b00-916a-11eb-9bf2-f6505488a228.png)

**Comment by 12Knocksinna** [comment]
The problem is that that distinguished name includes an apostrophe, so it needs some special handling. I'm fixing the issue in another script and will look at this afterwards.

**Comment by 12Knocksinna** [comment]
I've added code to handle the apostrophes. Please try again.
