### ISSUE TITLE
Private Channels not searched for activity

### ISSUE THREAD

**Issue by cleggj** [12Knocksinna/Office365itpros#30]
Hi guys.   Awesome script guys, TeamsGroupsActivityReport.ps1 works very well for our compliance policy of purging dormant and abandoned Teams.   Much appreciated!

We found that the script doesn't search Private Channels for activity and can flag a Team as inactive although it's in active use..   I've read somewhere that private conversations are stored in the User mailbox so not found in compliance searches.    Is it similar with chats in Private Channels, or is it simply permissions on the Channel itself ?

Wondering if this possible enhancement could be considered.

Thanks again guys!

**Comment by 12Knocksinna** [comment]
Private channel conversations are stored in user (member) mailboxes so they wouldn't be picked up. We're waiting for a Teams usage Graph API, which we hope will help solve the problem.
