### ISSUE TITLE
Issue with ReportManagersAndDirectReports.PS1

### ISSUE THREAD

**Issue by altonbrinja** [12Knocksinna/Office365itpros#32]
![image](https://user-images.githubusercontent.com/81647910/125840520-ca94f6fc-3757-4b84-a0ae-6a8398b34979.png)

**Comment by 12Knocksinna** [comment]
The code works just fine here. It looks like you're having problems with Get-User. Make sure that you have the latest EXO management module loaded and try to run the code line by like to check where things are going wrong. Note the input values and see why they might be a problem. This is all basic PowerShell, so you should be able to debug the code easily in a console or ISE.
