### ISSUE TITLE
Empty Members Array keep old entries

### ISSUE THREAD

**Issue by christophFeiker** [12Knocksinna/Office365itpros#33]
Great script at all. But I realized when a group does not have any member, the reporting line repeat all member information from previous. Therefore I needed to adjust the if-clause as follows:

`If (!($Members)) { 
        $CountOfMembers = 0
        [array]$TenantMembers = @()
        [array]$GroupMembers = @()
        [array]$GuestMembers = @()
        [array]$OtherMembers = @()
        $MemberNames = ""
    }`

**Comment by 12Knocksinna** [comment]
Thanks. I've added some code like you suggest to handle the situation where a group has no members,.
