### ISSUE TITLE
Error with SPOData.WebUrl.Substring - Lengt cannot be less than zero

### ISSUE THREAD

**Issue by ondraandy** [12Knocksinna/Office365itpros#34]
Hello,
can you help me please with this error? 
I don´t know how can I fix it.
Thanks!!
![Screenshot 2021-07-23 120223](https://user-images.githubusercontent.com/82198918/126767074-a1adbe50-5600-4ded-b821-7f8b17f0e84f.png)

**Comment by 12Knocksinna** [comment]
Looks like the call to populate the $SPOData variable didn't work. Do you have all the required Graph permissions consented for the program?

 $Uri = "https://graph.microsoft.com/v1.0/groups/" + $Group.Id + "/drive"
 **$SPOData** = Get-GraphData -AccessToken $Token -Uri $uri

Alternatively, if you're running this script against a tenant which doesn't use English language values for the document libraries in the SPO sites, you need to adjust these variables at the start of the script:

$SharedDocFolder = "/Shared%20Documents" # These values are to allow internationalization of the SPO document library URL. For French, this would be "/Documents%20partages" 
$SharedDocFolder2 = "/Shared Documents"  # Add both values

**Comment by stefanopagliuca** [comment]
Hi, did you solved the issue?
I have the same problem with the script. PErmission in MS Graph seems to be fine.
Thanks,
