### ISSUE TITLE
TeamsGroupsActivityReport.ps1 Running on 11k+ Teams

### ISSUE THREAD

**Issue by plodik** [12Knocksinna/Office365itpros#36]
I am trying to run your script TeamsGroupsActivityReport.ps1 on a huge Teams tenant - more then 11000 teams. It will run for hours and hours, however I am having various issues and errors. Is this capable to run on a huge tenant? Thanks a lot.

**Comment by 12Knocksinna** [comment]
Use the Graph-based version https://github.com/12Knocksinna/Office365itpros/blob/master/TeamsGroupsActivityReportV5.PS1 for large tenants. It's been tested at well over 30,000 teams.
