### ISSUE TITLE
Warnings based on Teams conversations aren't counted

### ISSUE THREAD

**Issue by NeighborGeek** [12Knocksinna/Office365itpros#39]
The NumberWarnings only counts warnings based on the Inbox and the SPO Document library.  It should also increment based on  warnings for Teams conversations.

**Comment by 12Knocksinna** [comment]
It's PowerShell... So you can add this if you like.

**Comment by 12Knocksinna** [comment]
BTW, I updated the script to V5.3 and added the warning for Teams in the new code.
