### ISSUE TITLE
Variable assigned but never used

### ISSUE THREAD

**Issue by nugatory776** [12Knocksinna/Office365itpros#48]
https://github.com/12Knocksinna/Office365itpros/blob/b9a5c525d93aa04778ae9a48da36f9f5c2b64dc9/ReportMailboxQuotaUsed.Ps1#L14

The variable $Mailbox is being assigned on line 14, but is never used anywhere else in the script.

**Comment by 12Knocksinna** [comment]
Easily fixed..
