### ISSUE TITLE
No Last SPO Activity in TeamsGroupsActivityReportV5.PS1

### ISSUE THREAD

**Issue by FabioOzitem** [12Knocksinna/Office365itpros#51]
Hello,

When i'm running TeamsGroupsActivityReportV5.PS1 I don't have any data in last SPO Activity column. Not sure if it's expected.

![image](https://user-images.githubusercontent.com/108076181/175316576-a686c59e-e9f0-4993-9c22-88779b480663.png)
Data from a test O365 Tenant.

Thank you !

**Comment by FabioOzitem** [comment]
Hello @12Knocksinna, 
Thank you for replying !
Yes i'm running version 5.5. I've added sites.read.all but column is still empty. I've tried as well with 5.6 and not much better.
!
[image](https://user-images.githubusercontent.com/108076181/181251547-8e839a46-e023-45d9-8fdb-a797ec5bd02a.png)

Do i miss some right ?

**Comment by 12Knocksinna** [comment]
What happens when you run:

$SPOUsageReportsURI = "https://graph.microsoft.com/v1.0/reports/getSharePointSiteUsageDetail(period='D180')"
   $SPOUsage = (Invoke-RestMethod -Uri $SPOUsageReportsURI -Headers $Headers -Method Get -ContentType "application/json") -Replace "...Report Refresh Date", "Report Refresh Date" | ConvertFrom-Csv 

Does any information show up in $SPOUsage?

**Comment by FabioOzitem** [comment]
Yes.

![image](https://user-images.githubusercontent.com/108076181/181261856-2e7bd128-9c1b-4579-becb-272f24b5d06a.png)

**Comment by 12Knocksinna** [comment]
I assume then that the $Datatable (hash table containing SPO usage data) is populated.

Later, the hash table is looked up for the usage data as each group is processed:

If ($G.SharePointURL -ne $Null) {    
      If ($Datatable[$G.SharePointURL]) { # Look up hash table to find usage information for the site
        $ThisSiteData = $Datatable[$G.SharePointURL]
        $SPOFileCount = $ThisSiteData.FileCount
        $SPOStorageUsed = $ThisSiteData.StorageUsed
        $SPOLastActivityDate = $ThisSiteData.LastActivityDate 
        If ($SPOLastActivityDate -ne $Null) {
           $DaysSinceLastSPOActivity = (New-TimeSpan -Start $SPOLastActivityDate -End $Today).Days }

You could check by populating $G with details of a group to see if the lookup works. For example:

$G = Get-UnifiedGroup -Identity "Test Group"
($Datatable[$G.SharePointSiteURL])

Name                           Value
----                           -----
StorageUsed                    1.54 GB
DisplayName                    Exchange GOMs
LastActivityDate               14/07/2022
FileCount                      8085

**Comment by FabioOzitem** [comment]
It makes me realise that $shareddocfolder wasn't configured for my french library...

``` PowerShell
   $SharedDocFolder = "/Documents%20partages" # These values are to allow internationalization of the SPO document library URL. For French, this would be "/Documents%20partages" 
   $SharedDocFolder2 = "/Documents partages"  # Add both values
```


I lost myself a bit after adding certificate auth to exchange online part :)

if Sites.Read.All, is really needed it could be worth adding it to comment section of your script where it's currently missing :)


```# V5.5 15-Jun-2022 Recoded way that check to renew access token worked and incorporated automatic fetch of latest Teams usage data
# V5.6 19-Jul-2022 Add email address of team owner to output and updated activity range for usage reports to 180 days
#
# https://github.com/12Knocksinna/Office365itpros/blob/master/TeamsGroupsActivityReport.ps1
#
# Needs the following Graph permissions:
# Group.Read.All, Reports.Read.All, User.Read.All, GroupMember.Read.All
#
#+-------------------------- Functions etc. -------------------------
```

**Comment by 12Knocksinna** [comment]
Funny... I realized that Sites.Read.All wasn't in the set listed earlier today and updated the script.
