### ISSUE TITLE
Cannot select Beta profile in ReportMFAStatusAdmins.PS1

### ISSUE THREAD

**Issue by TyrrellStephen** [12Knocksinna/Office365itpros#53]
Error:
PS C:\Users\..........\Office365itpros> .\ReportMFAStatusAdmins.PS1
Welcome To Microsoft Graph!
Select-MgProfile: C:\Users\tyrre\LocalRepos\PowerShellRepos\Office365itpros\ReportMFAStatusAdmins.PS1:8:18
Line |
   8 |  Select-MgProfile -Beta
     |                   ~~~~~
     | A parameter cannot be found that matches parameter name 'Beta'.

This is due to a typo in line 8 that should read 'Select-MgProfile Beta'

**Comment by 12Knocksinna** [comment]
Thanks. Fixed. (annoying and stupid bug)
