### ISSUE TITLE
Issue with $subject value after 01st execution

### ISSUE THREAD

**Issue by vitusq** [12Knocksinna/Office365itpros#55]
Hi
I notice an "issue" here. 
if the subject being searched for contains a **$xx** in it, the content search leaves it out and only takes all the other text around it.

This is the subject of an email I was using:
**[External Email] Free and $10 Udemy coupons by Learn Viral**

when the contentsearch is view, it can be seen that the subject being searched for is:
**[External Email] Free and Udemy coupons by Learn Viral**

This causes in accurate or new result at the end. what could be the issue here?

**Comment by 12Knocksinna** [comment]
What script is this problem in?

**Comment by vitusq** [comment]
> What script is this problem in?

PurgeMessagesWithContentSearch.PS1

**Comment by vitusq** [comment]
I also ran into another issue. When there's no special character similar to the earlier one i mentioned, and when every value entered is accepted fine by the script, it executes and does it thing, but at the very end, it throws the following error:



**Deleting items... ( 1 )
_**Cannot bind argument to parameter 'Identity' because it is null.
    + CategoryInfo          : InvalidData: (:) [Remove-ComplianceSearchAction], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Remove-ComplianceSearchAction
    + PSComputerName        : che01b.ps.compliance.protection.outlook.com**_

All done!**

**Comment by 12Knocksinna** [comment]
Try escaping the special character:

$Subject = "Special `$10 offer" - This needs to be done for PowerShell otherwise the special character is omitted.

**Comment by 12Knocksinna** [comment]
Does the search action exist? If it didn't (because it wasn't created beforehand), you'd get that error.

**Comment by vitusq** [comment]
I made a small addition to your script. I've just added in $ContentSearchName to avoid having to modify the search name in all the places of the script every time this needs to be executed. I've attached the script here for your reference. 

[DeleteEmailfromALLmailboxes.txt](https://github.com/12Knocksinna/Office365itpros/files/9197468/DeleteEmailfromALLmailboxes.txt)

Irrespective of the modification or not, it still throws the error:

**Deleting items... ( 1 )
Cannot bind argument to parameter 'Identity' because it is null.
+ CategoryInfo : InvalidData: (:) [Remove-ComplianceSearchAction], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Remove-ComplianceSearchAction
+ PSComputerName : che01b.ps.compliance.protection.outlook.com

All done!**

**Comment by vitusq** [comment]
> Try escaping the special character:
> 
> $Subject = "Special `$10 offer" - This needs to be done for PowerShell otherwise the special character is omitted.


This made it work right :D 

Thank you!

**Comment by vitusq** [comment]
> Does the search action exist? If it didn't (because it wasn't created beforehand), you'd get that error.

As i see in the script, there is a creation for the ComplianceSearch (line 28) and later for the ComplianceSearchAction (line 53)

**Comment by 12Knocksinna** [comment]
OK. I have made some updates to the script, including your suggestion of using a variable for the search name (and one for the purge action name). Also added ErrorAction to make sure that errors aren't reported when unnecessary. I'm closing this now.

**Comment by vitusq** [comment]
I'll give the updated script a try and will get back to you
