### ISSUE TITLE
TeamsGroupsActivityReport not suitable for private channels

### ISSUE THREAD

**Issue by alemas23** [12Knocksinna/Office365itpros#56]
Launching TeamsGroupsActivityReport.ps1, it can only detect the activity of teams with standard channels.
These commands can't analyze the activity of private channels. 
For teams with all private channels and General channel the output isn't reliable.
Are there any commands suitable for teams with private channels? 

@12Knocksinna @Swampen please give me a feedback
Regards
Alessandra

**Comment by 12Knocksinna** [comment]
Private channels aren't available to administrators. They are confined to members of the private channel. If you want to analyze the activity within a private channel, your account must be a member of those channels. That's why we ignore them. BTW, please use the Graph-based version of the script as that's the one we work on now.

**Comment by alemas23** [comment]
Thanks @12Knocksinna for your prompt reply,
the account, used to execute the script, is member of private channels.
I'm trying to test the script TeamsGroupsActivityReportV5

**Comment by 12Knocksinna** [comment]
There's still no way that I know to find the compliance records for private channels short of examining every record in the mailboxes of private channel members... that would take too long, so I'm not going to do it. Feel free to amend the code to your liking... it's just PowerShell.

**Comment by alemas23** [comment]
In my case it  would be enough to have the same output in team usage report by Teams Admin Portal (field: last activity date).
If there were activities (conversation or documentation) in private channel, in this date it has been recorded.
May you know which is the powershell command to extract this information?

**Comment by 12Knocksinna** [comment]
If I knew a way, I would implement it in the report.

**Comment by alemas23** [comment]
Ok, it's clear.
Thanks for your explanations.
