### ISSUE TITLE
Issue running script: Exception calling "Add" with "2" argument(s): - At line:51 char:34

### ISSUE THREAD

**Issue by QuintenPXS** [12Knocksinna/Office365itpros#60]
![image](https://user-images.githubusercontent.com/86714660/185609211-1b5fd7a6-53c3-4214-955a-fa25856a23ff.png)

Exception calling "Add" with "2" argument(s): "Item has already been added. Key in dictionary: ''  Key being added: ''"
At line:51 char:34
+ ... portSkus) { $SkuHashTable.Add([string]$Line.SkuId, [string]$Line.Disp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException

![image](https://user-images.githubusercontent.com/86714660/185609376-68b4a6fb-833b-4e7d-9cc2-55ed90ebe6a1.png)

any idea why or is this script no longer working/supported ?

thanks!

**Comment by colonelclaypoo** [comment]
I have the same issue but have not yet found the issue at first glance. Let it run through, though. Report is still generated.

**Comment by 12Knocksinna** [comment]
An attempt is being made to add a record that already exists in the hash table. It looks horrible but doesn't cause a problem. Some error handling would suppress it.
