### ISSUE TITLE
no support for hybrid teams users

### ISSUE THREAD

**Issue by stephanefavreza** [12Knocksinna/Office365itpros#61]
I noticed that this script was only returning a handful of users, closer inspection noted that it was only the cloud-only teams users. Noted line 9 is filtering on InterpretedUserType and since out tenants were migrated from OnPrem Skype for Business, the users were Hybrid InterpretedUserType's. 
So i hashed # out line 9 and added the following at line 47
 "InterpretedUserType"        = $user.InterpretedUserType 

![image](https://user-images.githubusercontent.com/52860874/185740756-9ad567f4-6774-46ee-8967-28a5efcb295d.png)

**Comment by 12Knocksinna** [comment]
Thanks. I've added an extra comment in the script and included the line to output the user type.
