### ISSUE TITLE
Large number of "No Owners Found"

### ISSUE THREAD

**Issue by damorris** [12Knocksinna/Office365itpros#62]
I ran this and out of 10,900 plus groups that are teams enabled its reporting 3742 as not having any owners. I am not done checking but I believe over 75% of those 3742 groups do have at least 1 owner.  Member and External Guest counts appear to be accurate.

**Comment by 12Knocksinna** [comment]
The code to find group owners uses a Graph query:

$Uri = "https://graph.microsoft.com/v1.0/groups/" + $Group.Id + "/owners?"
   [array]$GroupData = Get-GraphData -Uri $Uri -AccessToken $Token

Can you try running this against a group that has an owner that's reported as ownerless to see what's returned? You could try this code using the Graph Explorer if you like.

**Comment by 12Knocksinna** [comment]
By the way, just to be sure, what script are you referring to?

**Comment by 12Knocksinna** [comment]
OK. I found a better way to check for owners. The script is updated to V5.8 with the fix. Please try that.
