### ISSUE TITLE
Report for Specific Teams

### ISSUE THREAD

**Issue by htsid5** [12Knocksinna/Office365itpros#63]
I have 10K teams, i want to get report of just 100 teams. How I can achieve it?

**Comment by 12Knocksinna** [comment]
Same answer as I gave to the same question on Office365itpros.com:

Instead of fetching all Teams to report, use another method to report just selected teams. For example, you could apply a filter to find specific teams, or you could read in the details of teams to report from a CSV file. It’s really up to you. The report operates on whatever teams it’s given to process.

**Comment by htsid5** [comment]
I am searching your script but not finding way of importing from CSV. To get full report and search for Teams is the problem as 10000 teams are hard to process and script is ending abruptly. 

I was able to run it once but then i found that many teams are missing owner but they have owner.

**Comment by htsid5** [comment]
I am using V5.8 15-Sep-2022 Improved check for groups with no owners, but it is not adding owner and saying No Owner Found in CSV.

**Comment by 12Knocksinna** [comment]
Well, it's PowerShell, so how about doing some debugging? I can't see the data in your tenant, so you'll have to run the code and see what's returned when the script processes this code for a group that has owners that the script thinks has no owners.
When you get this information, let me know and I will have a look. The code works OK here.

# Get Group Owners
   $Uri = "https://graph.microsoft.com/v1.0/groups/" + $Group.Id + "/owners?"
   [array]$GroupData = Get-GraphData -Uri $Uri -AccessToken $Token
   If ($GroupData[0].'@odata.type' -eq '#microsoft.graph.user') { # Found a group owner, so extract names
      $OwnerNames = $GroupData.DisplayName -join ", " 
      $GroupOwnerEmail = $GroupData[0].Mail }
   Else { # ownerless group
       $OwnerNames = "No owners found"
       $GroupOwnerMail = $Null }
   # Get extended group properties

**Comment by 12Knocksinna** [comment]
I ran the code this morning and found 12 groups of 232 reported with no owners. This was because an account that used to be the sole owner of these groups had been deleted.

To check the accuracy of the report, find the group in the $Groups array. For example:

 $Group = $Groups | ? {$_.Displayname -eq "Mail filter patent"}

Now check what Exchange Online says about the ownership:

get-unifiedgrouplinks -LinkType Owner -Identity $Group.id

If this cmdlet returns an owner (or owners), we have a problem, and I am interested. So far, I haven't found a situation where a group is misreported. If you do find one, please let me know the details of the group by running these commands:

$Uri = "https://graph.microsoft.com/v1.0/groups/" + $Group.Id + "/owners?"
[array]$GroupData = Get-GraphData -Uri $Uri -AccessToken $Token
$Groupdata

What's in $GroupData?

**Comment by htsid5** [comment]
Get-unifiedgroup links is getting me owner but CSV has no owner. 

Running this 

$Uri = "https://graph.microsoft.com/v1.0/groups/" + $Group.Id + "/owners?"
[array]$GroupData = Get-GraphData -Uri $Uri -AccessToken $Token
$Groupdata

is not working because even if i try to run function of token, it is not helping. If you can kindly paste the the code which is getting Token as well.

**Comment by 12Knocksinna** [comment]
The code to get the token is in the script.


Tony Redmond (from a mobile device)
________________________________

**Comment by htsid5** [comment]
$GroupData has name of 2 owners. myself and one another.

**Comment by 12Knocksinna** [comment]
Can you paste the contents of $GroupData | FL


Tony Redmond (from a mobile device)
________________________________

**Comment by htsid5** [comment]
Can i send privately for privacy reasons?

**Comment by 12Knocksinna** [comment]
Just edit the email addresses and replace them with something like ***@***.***


Tony Redmond (from a mobile device)
________________________________

**Comment by htsid5** [comment]
PS C:\Users\hsiddiqui-admin> $Groupdata | fl


@odata.type       : #microsoft.graph.user
id                : 37f4cad0-8d7f-4c81-9c65-********
businessPhones    : {+1 ********}
displayName       : Siddiqui, Hasan
givenName         : Hasan
jobTitle          : ********
mail              : hsid********@********
mobilePhone       : +1 ********
officeLocation    : ********
preferredLanguage :
surname           : Siddiqui
userPrincipalName : hsid********@********

@odata.type       : #microsoft.graph.user
id                : 191c40ae-00d2-4b49-8216-********
businessPhones    : {+1 ********}
displayName       : Eye, Philip
givenName         : Philip
jobTitle          : ********
mail              : ********@********
mobilePhone       : +1 ********
officeLocation    : ********
preferredLanguage :
surname           : Eye
userPrincipalName : ********@********

**Comment by 12Knocksinna** [comment]
And this group returns no owners in the output report?


Tony Redmond (from a mobile device)
________________________________

**Comment by htsid5** [comment]
Yes, i wish i can show you screenshot or attach it. but here you go

GroupName | ManagedBy | ContactEmail | Visibility | Members | External Guests | Description | Sensitivity Label | Team Enabled | Last Teams message | Number Teams messages | Last Email Inbox | Number Email Inbox
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Hasan Teams 8/24/2022 | No owners found |   |   |   |   |   |   | FALSE | N/A | 0 | 8/24/2022 14:46 | 1
Hasan   Teams Group 04162020 | No owners found |   |   |   |   |   |   | FALSE | N/A | 0 | 2/15/2022 18:34 | 12
Hasan Teams Group 06102021 | No owners found |   |   |   |   |   |   | FALSE | N/A | 0 | 6/10/2021 16:03 | 1
Hasan   Teams Group 07072021 | No owners found |   |   |   |   |   |   | FALSE | N/A | 0 | 7/7/2021 17:25 | 1

**Comment by htsid5** [comment]
Also the script end report looks misleading as well. Took 8 hours to process 10000 groups:

Results - Teams and Microsoft 365 Groups Activity Report V5.8
-------------------------------------------------------------
Number of Microsoft 365 Groups scanned:                          10731
Potentially obsolete groups (based on document library activity: 10007
Potentially obsolete groups (based on conversation activity):    8186
Number of Teams-enabled groups:                                  1
Number of archived teams:                                        0
Percentage of Teams-enabled groups:                              0.01%

Total Elapsed time:  44923.62 seconds

**Comment by 12Knocksinna** [comment]
I’d expect the report to take a long time to run for that many groups. You could run it as an Azure Automatan scheduled runbook if you didn’t want to look at it running. Some alternation to the code would be needed, but not too extensive.


Tony Redmond (from a mobile device)
________________________________

**Comment by 12Knocksinna** [comment]
I am puzzled. The Graph reports two owners so the code check should be happy with that. I don’t see a problem in my tenant. There’s something odd that I can’t quite figure out.

But this is PowerShell, so feel free to do some debugging yourself. This is not a product. Anyone can update the code.


Tony Redmond (from a mobile device)
________________________________

**Comment by htsid5** [comment]
also what i noticed is, teams stats are missing completely. Every group, it is saying Teams Enabled is False. That is why teams last message and number of teams message is missing data. 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/hsiddiqui-admin/AppData/Local/Temp/2/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/hsiddiqui-admin/AppData/Local/Temp/2/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Team Enabled | Last Teams message | Number Teams messages
-- | -- | --




</body>

</html>

**Comment by 12Knocksinna** [comment]
Teams stats are found by running this code:

$Uri = "https://graph.microsoft.com/beta/reports/getTeamsTeamActivityDetail(period='D180')?`$format=application/json"
[array]$TeamsData = Get-GraphData -Uri $Uri -AccessToken $Token

This call requires the Reports.Read.All permission. I assume the app you're using to run the script has this permission?

Try running the code and see if you can retrieve any Teams activity information.

**Comment by 12Knocksinna** [comment]
The GetTeamsStats function takes the data retrieved for Teams usage and creates a hash table called $TeamsUsageHash. It looks like this:

$TeamsUsageHash

Name                           Value
----                           -----
b540f837-1bd1-413b-8f8e-60f... @{Id=b540f837-1bd1-413b-8f8e-60f7f21b42de; DisplayName=HR Questions and Answers; Priv...
84929dd0-7cba-456b-81ab-a5b... @{Id=84929dd0-7cba-456b-81ab-a5bd3331ef94; DisplayName=French Wine Lovers (Team); Pri...
fee4a526-fd91-46e9-a45b-cdb... @{Id=fee4a526-fd91-46e9-a45b-cdb92f929602; DisplayName=Corona Virus News; Privacy=Pri...
9940af0b-35fc-407c-b806-3fb... @{Id=9940af0b-35fc-407c-b806-3fb84ecd11fe; DisplayName=; Privacy=Private; Posts=0; Re...

To get the usage data for a team-enabled group, the script looks up the hash table using the group identifier. If the hash table isn't there or isn't populated, you won't be able to find any information and all your groups won't be considered team-enabled.
