### ISSUE TITLE
Audit Log retention?

### ISSUE THREAD

**Issue by myatix** [12Knocksinna/Office365itpros#65]
Hi,

I was just looking at the "FindOldGuestUsers.ps1" script and can see that this uses the "Get-AzureADAuditSignInLogs" which is part of AzureADPreview module. The issue is that the AuditLog is limited to 30 days, so I was wondering how this script is suppose to work?

Also when you run the script you very quickly seem to get hit by MS throttling

![image](https://user-images.githubusercontent.com/48433526/194856612-776abaf1-7eb8-4747-9ab2-28cdd6c35d1e.png)

I see the concept but in reality, this doesn't work passed 30 days, which is a little irrelevant.

**Comment by 12Knocksinna** [comment]
It's an old script that uses the soon to be retired Azure AD module. Today, I would use the Microsoft Graph PowerShell SDK and the Get-MgAuditSignInLogs cmdlet. I have no idea why you're being throttled.

**Comment by 12Knocksinna** [comment]
I updated the script to use SDK cmdlets. It shouldn't be throttled now because the code doesn't read the audit logs. Instead, it gets the last sign in date from the user account.
