### ISSUE TITLE
Doesn't include 3rd party Software authenticators

### ISSUE THREAD

**Issue by convictushome** [12Knocksinna/Office365itpros#73]
added the following to the switch on the foreach authenticator method function so that users with 3rd party OTP apps are included in the report correctly

"#microsoft.graph.softwareOathAuthenticationMethod"  { # Software Authenticator App
               $AuthType     = '3rd party AuthenticatorApp'
               $AuthTypeDetails = $MfaMethod.AdditionalProperties["displayName"] }

**Comment by 12Knocksinna** [comment]
OK. You could have updated the code in the repro and I would have accepted the request!
