### ISSUE TITLE
Getting (400) Bad Request Error Here

### ISSUE THREAD

**Issue by ghost** [12Knocksinna/Office365itpros#79]
I’ve tried running this script but getting this error. Could you please help me resolve it. 

Accessing the Graph to get user sign-in data...
Invoke-RestMethod: The remote server returned an error: (400) Bad Request.
At Cr Users \admin\Desktop\lastsignin. ps1:31 char :16 
+ … gnInData = (Invoke-RestMethod -Uri $URI -Headers $Headers -Method Get ...
: Invalidoperation: (System. Net. HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], webException
A11 done. 0 accounts processed - output available in c:\Temp\ReportUserSignin.csv.
PS C:\WINDOWS\system32> |

![IMG_6113](https://user-images.githubusercontent.com/129406605/228871913-6fd23135-22a7-427d-a9b8-6873773cbc9c.jpeg)

Could you please be able to help me resolve it.

**Comment by replyonly** [comment]
The script contained an ‘ before $top=999 on line 30.  I removed this ' and the script ran successfully.

**Comment by apgoncalves** [comment]
I´m getting the same error. The problem is, if I remove de backtick, $select and $top is ignored.

**Comment by 12Knocksinna** [comment]
This is an old script (3 years) and I wouldn't use this approach to get sign in data for users anymore. 

https://office365itpros.com/2022/09/29/underused-accounts-report/ explains how to use the Microsoft Graph PowerShell SDK cmdlet Get-MgUser to fetch information about users (including signins) with a command like:

[Array]$Users = Get-MgUser -Filter "assignedLicenses/`$count ne 0 and userType eq 'Member'" -ConsistencyLevel eventual -CountVariable Records -All -Property signInActivity |   Sort-Object DisplayName

I think that's a better approach.

Anyway, the reason why the call is failing is that the Azure AD team has limited fetches to 120 objects at a time. That's a recent change:

{"error":{"code":"UnknownError","message":"{\"@odata.context\":\"http://reportingservice.act
ivedirectory.windowsazure.com/auditLogs/$metadata#Edm.String\",\"value\":\"Cannot query
data for more than 120 users at a time.\"}","innerError":{"date":"2023-04-01T09:43:21","requ
est-id":"c51d7e23-0469-405d-9170-4206e25af69d","client-request-id":"c51d7e23-0469-405d-9170-
4206e25af69d"}}}

Change the $top=999 to $top=100 and the command will run. The backtick is necessary to escape the $ character in PowerShell.
