### ISSUE TITLE
(401) Unauthorized -  GetUserSignInDataGraph.PS1

### ISSUE THREAD

**Issue by AlanDevOps** [12Knocksinna/Office365itpros#80]
I'm looking for help similar to https://github.com/12Knocksinna/Office365itpros/issues/50

This is on a tenant with many users.

I keep getting (401) Unauthorized. around an hour into it running.

**Comment by 12Knocksinna** [comment]
It's likely that the access token is timing out. The default access token lasts an hour and then expires. You can include some code to renew the token after 55 minutes or so and all will be well.
