### ISSUE TITLE
You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by MarcLaf** [12Knocksinna/Office365itpros#86]
When running this script I keep getting the following for each module. I'm not running it as Administrator and I've changed the -Scope parameter to CurrentUser. 

Checking and updating module AIPService
InvalidOperation: Update-Office365PowerShellModules.ps1:30
Line |
  30 |       $CurrentVersion = $CurrentVersion.Major.toString() + "." + $Curr …
     |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

**Comment by 12Knocksinna** [comment]
What's in $CurrentVersion?

**Comment by MarcLaf** [comment]
The version string from the module object.

**Comment by 12Knocksinna** [comment]
Yeah, so is it getting a value? What module is being processed at the time? Forgive me for saying this, but you'll have to debug the script to find the problem in your environment. I cannot see what data is in front of you. I've just run the script with admin permissions (which it needs) on a new PC and it works perfectly.

**Comment by MarcLaf** [comment]
Right I’ve been trying to off and on. I mentioned in the first post that I
did not run as administrator because I only want to install for current
user (and modified the script to do so), not all users as is originally
built. I’m thinking this could be a reason although I’m not sure how that
would affect this issue. It does it for all modules.

I’ll keep at it then.

**Comment by 12Knocksinna** [comment]
I still think you need to run PowerShell as an administrator to be able to install or update modules.

**Comment by 12Knocksinna** [comment]
I'm closing this issue.

**Comment by MarcLaf** [comment]
I know this is closed but I figured out the issue. It wasn't Admin related, it was Windows PowerShell vs PowerShell 7. My default version is PowerShell 7 and I use the majority of the modules there. This script needs Windows PowerShell for what I'm guessing are a few modules dependent on that version. I have no idea if there is a check to implement whether or not it's being run in Windows PowerShell vs PowerShell 7.

**Comment by 12Knocksinna** [comment]
That could be it. I do use the Install-Module and Update-Module cmdlets...
