### ISSUE TITLE
Teams Activity Data returning only 200 items

### ISSUE THREAD

**Issue by ashwanisharma88** [12Knocksinna/Office365itpros#90]
How we will get data for all users. This script generates report for only 200 teams. I need to generate it for up to 2k teams.

**Comment by 12Knocksinna** [comment]
And what script are you referring to? I can't tell from the title.

**Comment by ashwanisharma88** [comment]
> And what script are you referring to? I can't tell from the title.

ReportTeamsActivityGraph.PS1

**Comment by 12Knocksinna** [comment]
It's because the Graph only fetches 200 items at a time to minimize resource usage. If the script doesn't include pagination, it won't fetch the remaining team data. I've updated the script with the necessary code.
