### ISSUE TITLE
Small bug with Fix

### ISSUE THREAD

**Issue by jjdrost** [12Knocksinna/Office365itpros#91]
is:open label:bug querry more then 400 sites, msgraph stops working and the process will freeze. FIX, change line 58 - Sleep -Milliseconds 1000 # Brief pause before next channel

**Comment by 12Knocksinna** [comment]
What script is this?

**Comment by jjdrost** [comment]
FindTeamChannelsWithWiki.PS1

**Comment by 12Knocksinna** [comment]
Fixed.
