### ISSUE TITLE
issue with line 38 on Analyze-MailtrafficUsers.PS1

### ISSUE THREAD

**Issue by stephanefavreza** [12Knocksinna/Office365itpros#92]
Analyze-MailtrafficUsers.PS1

Line 38 SharedMailbox is missing d 

[array]$Mbx = Get-ExoMailbox -RecipientTypeDetails UserMailbox, SharedMailbox -ResultSize Unlimited | Sort-Object DisplayName

:)

**Comment by 12Knocksinna** [comment]
Fixed. Thanks for highlighting my lack of competence with copy and paste!
