### ISSUE TITLE
new error for GetUserSignInDataGraph

### ISSUE THREAD

**Issue by benseo** [12Knocksinna/Office365itpros#93]
Hi, I've been using this script which ran perfectly fine until i started getting bunch of errors shown below; I'm not sure what it means, and how to address it. 

Get-Date : Cannot bind parameter 'Date' to the target. Exception setting "Date": "Cannot convert null to type "System.DateTime"."
At C:\scripts\GetUserSingIn-NonInteractive-Graph.PS1:59 char:29
+ ... n = Get-Date($User.SignInActivity.lastNonInteractiveSignInDateTime) - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-Date], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Commands.GetDateCommand
 
New-TimeSpan : Cannot bind parameter 'Start'. Cannot convert value "Never or > 180 days" to type "System.DateTime". Error: "The string was not recognized as a valid DateTime. There is an unknown word starting at index 0."
At C:\scripts\GetUserSingIn-NonInteractive-Graph.PS1:60 char:40
+       $DaysSinceSignIn = (New-TimeSpan $LastSignIn).Days }
+                                        ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-TimeSpan], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.NewTimeSpanCommand

**Comment by 12Knocksinna** [comment]
Maybe it's just PowerShell being more precise about date checking. I have amended the script and it seems to be fine now. BTW, the Microsoft Graph PowerShell SDK is an easier way to get this kind of data - no app required.

**Comment by benseo** [comment]
Thanks for response, sorry for bug again, but still getting below in ISE/PS core7. If below error pertains to merely sensitivity related warnings, I'll be good as long as users login data output is still to be accurate, trustworthy when the errors shown. thanks much Tony. Also, I wonder if I can use this script directly in MS graph PowerShell SDK as is or require re-write.

Get-Date : Cannot bind parameter 'Date' to the target. Exception setting "Date": "Cannot convert null to type "System.DateTime"."
At C:\scripts\GetUserSignIn-New_Graph.PS1:89 char:35
+      Created            = Get-Date($User.CreatedDateTime) -format g
+                                   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-Date], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Commands.GetDateCommand

**Comment by 12Knocksinna** [comment]
No idea what's happening. The code works fine at my end. Try the version that uses the Graph SDK. It's much shorter and doesn't need an app...

https://github.com/12Knocksinna/Office365itpros/blob/master/GetUserSignInDataGraphSDK.PS1
