### ISSUE TITLE
FindObsoleteGuestsByActivityV3 script with error

### ISSUE THREAD

**Issue by funmix** [12Knocksinna/Office365itpros#94]
Script : FindObsoleteGuestsByActivityV3.PS1
Issue : New-TimeSpan : The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of 
the parameters that take pipeline input.
At line:54 char:42
+      $AccountAge = ($G.CreatedDateTime | New-TimeSpan).Days
+                                          ~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-TimeSpan], ParameterBindingException
    + FullyQualifiedErrorId : InputObjectNotBound,Microsoft.PowerShell.Commands.NewTimeSpanCommand

**Comment by 12Knocksinna** [comment]
Looks like the change to the Microsoft Graph PowerShell SDK V2 screwed this up because the creation date is not fetched unless you either specify it (with Get-MgUser) or use the Get-MgBetaUser cmdlet. I've fixed this and some other issues I see...
